DATABASES:
    CREATE:
        - database-name1
        - database-name2
        - database-name3
        - database-name4
    REMOVE:
        - database-name3
        - database-name4
USERS:
    CREATE:
        - USERNAME: username1
          PASSWORD: password1
        - USERNAME: username2
          PASSWORD: password2
        - USERNAME: username3
          PASSWORD: password3
    REMOVE:
        - username3
    GRANT-ALL:
        - USER: username1
          DATABASE: database-name1
        - USER: username1
          DATABASE: database-name2
    GRANT-SELECT:
        - USER: username2
          DATABASE: database-name1
        - USER: username2
          DATABASE: database-name2
    GRANT-SELECT-TABLE:
        - USER: username2
          DATABASE: database-name1
          TABLE: tablename
        - USER: username1
          DATABASE: mysql
          TABLE: user